// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiZhrr8FgkLudivK_XiKgOXdc2kUE025E',
    appId: '1:791734182066:web:c317d1cc5288d46f1f29ab',
    messagingSenderId: '791734182066',
    projectId: 'final-project-ppb-35cb4',
    authDomain: 'final-project-ppb-35cb4.firebaseapp.com',
    storageBucket: 'final-project-ppb-35cb4.firebasestorage.app',
    measurementId: 'G-XMK00TXY8F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO0BAzOC4tvfEJml6eVNZKZNRMVXu9DvY',
    appId: '1:791734182066:android:fc0e7c61c4caf2ef1f29ab',
    messagingSenderId: '791734182066',
    projectId: 'final-project-ppb-35cb4',
    storageBucket: 'final-project-ppb-35cb4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB17r3b2A1W-iF1XSjOzbY7BRj3KQRtpus',
    appId: '1:791734182066:ios:1f85819f5a35c4a01f29ab',
    messagingSenderId: '791734182066',
    projectId: 'final-project-ppb-35cb4',
    storageBucket: 'final-project-ppb-35cb4.firebasestorage.app',
    iosBundleId: 'com.example.donaseeFinalProjectPpb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB17r3b2A1W-iF1XSjOzbY7BRj3KQRtpus',
    appId: '1:791734182066:ios:1f85819f5a35c4a01f29ab',
    messagingSenderId: '791734182066',
    projectId: 'final-project-ppb-35cb4',
    storageBucket: 'final-project-ppb-35cb4.firebasestorage.app',
    iosBundleId: 'com.example.donaseeFinalProjectPpb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiZhrr8FgkLudivK_XiKgOXdc2kUE025E',
    appId: '1:791734182066:web:49058f0b938fce2f1f29ab',
    messagingSenderId: '791734182066',
    projectId: 'final-project-ppb-35cb4',
    authDomain: 'final-project-ppb-35cb4.firebaseapp.com',
    storageBucket: 'final-project-ppb-35cb4.firebasestorage.app',
    measurementId: 'G-BNXG9K29ZE',
  );

}